# resource_types:
#   - name: pull-request
#     type: docker-image
#     source:
#       repository: teliaoss/github-pr-resource

resources:
  - name: source
    type: git
    icon: github
    source:
      uri: git@github.com:petewall/segment-clock.git
      branch: master
      private_key: ((github-repo-key))

  - name: ota-source
    type: git
    icon: github
    source:
      uri: git@github.com:petewall/ota-service.git
      branch: master
      paths:
        - ci/tasks/upload.yml
      private_key: ((github-repo-key))

  - name: version
    type: semver
    icon: github
    source:
      driver: git
      uri: git@github.com:petewall/segment-clock.git
      branch: master
      file: version
      private_key: ((github-repo-key))
      commit_message: "[ci skip] bump to %version%"

  - name: platformio
    type: docker-image
    icon: docker
    source:
      repository: petewall/platformio
      username: ((dockerhub-username))
      password: ((dockerhub-password))

  # - name: pull-requests
  #   type: pull-request
  #   source:
  #     repository: petewall/segment-clock
  #     access_token: ((github-access-token))

jobs:
  - name: test
    plan:
      - in_parallel:
        - get: platformio
        - get: source
          trigger: true
      - task: run-check
        image: platformio
        config:
          platform: linux
          params:
            FIRMEARE_VERSION: 0.0.0
            GITHUB_SSH_KEY: ((github-repo-key))
            OTA_HOSTNAME: http://wallserver.local
            OTA_PORT: "8266"
            WIFI_SSID: fake-ssid
            WIFI_PASSWORD: fake-password
          inputs:
            - name: source
          run:
            dir: source
            path: make
            args: ["check"]
      - task: run-test
        image: platformio
        config:
          platform: linux
          params:
            FIRMEARE_VERSION: 0.0.0
            GITHUB_SSH_KEY: ((github-repo-key))
            OTA_HOSTNAME: http://wallserver.local
            OTA_PORT: "8266"
            WIFI_SSID: fake-ssid
            WIFI_PASSWORD: fake-password
          inputs:
            - name: source
          run:
            dir: source
            path: make
            args: ["test"]

  - name: build-firmware
    serial_groups: [version]
    plan:
      - in_parallel:
        - get: platformio
          passed:
            - test
        - get: version
          passed:
            - bump-minor-version
        - get: source
          passed:
            - test
          trigger: true
        - get: ota-source
      - task: build
        image: platformio
        file: source/ci/tasks/build.yml
        params:
          GITHUB_SSH_KEY: ((github-repo-key))
          OTA_HOSTNAME: http://wallserver.local
          OTA_PORT: "8266"
          WIFI_SSID: ((wifi-ssid))
          WIFI_PASSWORD: ((wifi-password))
      - task: upload-firmware
        file: ota-source/ci/tasks/upload.yml
        params:
          OTA_SERVICE: http://wallserver.local:8266
          TYPE: segment-clock
      - put: version
        params:
          bump: patch
          file: version/version

  - name: bump-minor-version
    serial_groups: [version]
    plan:
      - put: version
        params:
          bump: minor
